CREATE TABLE Users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(50) NULL,
    LastName VARCHAR(50) NULL,
    email VARCHAR(50) NULL,
    password VARCHAR(255) NULL,
    status SMALLINT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
